### PR TITLE
Feature/add new methods

### PR DESCRIPTION
**Pull request by gabrielHosino**
#### What is the purpose of this pull request?
Add getBrandById and getCategoryById to the catalog client. 
Add listInventoryBySku to logistics client

#### What problem is this solving?
We need to get the info from those methods responses to use in a new app.

#### How should this be manually tested?

- Create a simple IO service
- Import io-clients locally
- Call the new methods

#### Types of changes
- [ ] Refactor (non-breaking change that only makes the code better)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

#### Chores checklist
- [x] Update `CHANGELOG.md`

### CODE REVIEW

**Comment by gabrielHosino** [comment]
Hello, i'm not sure how to update de CHANGELOG because there is already an unreleased section there. Should I just add my changes to that section? Let me know and i'll make the changes!

Thanks!

**Comment by fabianaferreira** [comment]
> Hello, i'm not sure how to update de CHANGELOG because there is already an unreleased section there. Should I just add my changes to that section? Let me know and i'll make the changes!
> 
> Thanks!

Hi, @gabrielHosino! Ideally, you add what you changed to the Unreleased section and once we merge, we can release the version and it will automatically put this section that you edit as a released version.

**Review by fabianaferreira — APPROVED** [review]
LGTM

Let's just updated the `CHANGELOG.md` so we can have the changes in there. Thank you so much for your contribution! 🚀

**Comment by gabrielHosino** [comment]
@fabianaferreira Thanks! I added my changes to the CHANGELOG.

**Comment by gabrielHosino** [comment]
Hi @fabianaferreira , I saw that the method getCategoryById was already been added on the PR#46, so i changed my PR and removed that from it. 

Also i made a small change to the getProductsAndSkus method on catolog client to use query params.

I hope this is alright, please let me know if there is any problem.

Thanks!

**Review by fabianaferreira — APPROVED** [review]
LGTM.

To release it after merging, you can follow the steps that are in this [section](https://github.com/vtex/io-clients#releasing).

@lucis, can you check if you release the last version that is in the main branch? It seems that the changelog has not been updated.

**Pull request merged**
